owncloud/ocis-reva

pkg/command/server.go, pkg/config/config.go
We want to start only the the oidcprovider for `ocis demo`. This allows passing in arbitrary reva configurations and starting them in parallel.
=> allow passing in an arbitrary reva config map

changelog/unreleased/change-default-namespace.md, pkg/command/frontend.go, pkg/config/config.go, pkg/flagset/frontend.go
Currently, cross storage etag propagation is not yet implemented, which prevents the desktop client from detecting changes via the PROPFIND to /. / is managed by the root storage provider which is independend of the home and oc storage providers. If a file changes in /home/foo, the etag change will only be propagated to the root of the home storage provider.
This change jails users into the `/home` namespace, and allows configuring the namespace to use for the two webdav endpoints using the new environment variable `WEBDAV_NAMESPACE_JAIL` which affects both endpoints `/dav/files` and `/webdav`.
This will allow us to focus on getting a single storage driver like eos or owncloud tested and better resembles what owncloud 10 does.
To get back the global namespace, which ultimately is the …
=> change default ocdav namespace

.drone.star, changelog/unreleased/pull-77.md, pkg/command/frontend.go, pkg/config/config.go, pkg/flagset/frontend.go
after https://github.com/owncloud/ocis-reva/commit/fbf131c6b276f1b51e759666c450675e33d9e2db the path for the "new" webdav path does not contain a username /remote.php/dav/files/textfile0.txt it used to be /remote.php/dav/files/oc/einstein/textfile0.txt
So it lost oc/einstein
This PR allows setting up different namespaces for /webav and /dav/files:
- /webdav is jailed into /home - which uses the home storage driver and uses the logged in user to construct the path
- /dav/files is jailed into /oc - which uses the owncloud storage driver and expects a username as the first path segment
this mimics oc10
related: https://github.com/owncloud/ocis-reva/pull/68
=> allow different namespaces

changelog/unreleased/76, pkg/flagset/storageroot.go, pkg/flagset/users.go
=> set correct flag type

changelog/unreleased/issue-87.md, pkg/command/storagehome.go, pkg/command/storagehomedata.go, pkg/command/storageoc.go, pkg/command/storageocdata.go, pkg/command/storageroot.go, pkg/config/config.go, pkg/flagset/storagehome.go, pkg/flagset/storagehomedata.go, pkg/flagset/storageoc.go, pkg/flagset/storageocdata.go, pkg/flagset/storageroot.go
Enhancement: expose owncloud storage driver config in flagset
Three new flags are now available:
- scan files on startup to generate missing fileids
default: `true`
env var: `REVA_STORAGE_OWNCLOUD_SCAN`
cli option: `--storage-owncloud-scan`
- autocreate home path for new users
default: `true`
env var: `REVA_STORAGE_OWNCLOUD_AUTOCREATE`
cli option: `--storage-owncloud-autocreate`
- the address of the redis server
default: `:6379`
env var: `REVA_STORAGE_OWNCLOUD_REDIS_ADDR`
cli option: `--storage-owncloud-redis`
fixes https://github.com/owncloud/ocis-reva/issues/87
=> expose owncloud storage driver config in flagset

README.md
=> [Tests-only] documentation about running oC10 API tests

.drone.star, README.md, changelog/unreleased/issue-89.md, pkg/flagset/storagehome.go, pkg/flagset/storageoc.go
The flags that let reva storage providers announce that they expose a data server now defaults to true:
`REVA_STORAGE_HOME_EXPOSE_DATA_SERVER=1`
`REVA_STORAGE_OC_EXPOSE_DATA_SERVER=1`
fixes https://github.com/owncloud/ocis-reva/issues/89
=> storage providers now default to exposing data servers

changelog/unreleased/fix-eos-config.md, pkg/command/storagehome.go, pkg/command/storagehomedata.go, pkg/command/storageoc.go, pkg/command/storageocdata.go, pkg/command/storageroot.go
required for https://github.com/owncloud/ocis/pull/172
=> fix eos config

README.md, docs/users.md
1. demo is not the default user driver anymore see https://github.com/owncloud/ocis-reva/pull/113/files#diff-b9b822f0b45bd757e42670a061db9b70L89
2. update the LDAP default settings, see https://github.com/owncloud/ocis-reva/blob/master/pkg/flagset/authbasic.go
=> fix user related documentation

README.md, docs/testing.md
1. a redis server is needed for the tests
2. the documentation of tests was moved to https://github.com/owncloud/ocis-reva/blob/master/docs/testing.md in #113 
so  no need to have it also in the README
=> [Tests-only] delete test documentation from README

README.md
the current documentation seems to live in https://owncloud.github.io/extensions/ocis_reva/
=> fix links to documentation

pkg/command/frontend.go
Removed "chunking" attribute in the DAV capabilities.
Please note that chunking v2 is advertised as "chunking 1.0" while
chunking v1 is the attribute "bigfilechunking" which is already false.
@butonic as discussed
=> Don't advertise unsupported chunking v2

changelog/unreleased/update-reva-to-20200507093219.md, go.mod, go.sum
Mostly to unblock https://github.com/owncloud/ocis/pull/259 but also brings a few more interesting fixes
=> Update reva to v0.1.1-0.20200512135421

.drone.star
All issues were solved, we can enable this on CI
Fixes https://github.com/owncloud/ocis-reva/issues/182
=> Enable litmus tests for copymove

.drone.star
This PR makes sure a user is created with skeleton files in ocis and is related with PR https://github.com/owncloud/core/pull/37363
https://github.com/owncloud/ocis-reva/issues/167
=> [Tests-only] Create test-skeleton files while creating user

changelog/unreleased/add-tus-global-capabilities.md, pkg/command/frontend.go, pkg/config/config.go, pkg/flagset/frontend.go
Added global TUS capability in the config structure.
Added config switches for the advertised max chunk size and http method
override.
Requires https://github.com/cs3org/reva/pull/775 to work.
=> Make global TUS capability configurable

changelog/unreleased/update-reva-to-20200603071553.md, go.mod, go.sum
=> Update reva to v0.1.1-0.20200603071553-e05a87521618

changelog/unreleased/update-reva-to-20200629.md, go.mod, go.sum
Brings in public link single file share
=> Update reva to v0.1.1-0.20200629094927-e33d65230abc

changelog/unreleased/update-reva-to-20200630.md, go.mod, go.sum
Fixes for public link Webdav COPY and password field in response.
=> Update reva to v0.1.1-0.20200630075923-39a90d431566

.drone.star, docs/testing.md
See core PR https://github.com/owncloud/core/pull/37616 - all these tags no longer need to be specified.
`skipOnOcis` is the important one.
PR #321 demonstrated that this will work.
=> [Tests-Only] Remove unneeded TestAlsoOnExternalUserBackend local_storage skipOnLDAP tags

.drone.star, changelog/unreleased/update-reva-to-20200701.md, go.mod, go.sum
For  https://github.com/owncloud/ocis-reva/issues/327
=> Update reva to 20200701

.drone.star
Part of issue https://github.com/owncloud/user_ldap/issues/578
Remove the offending `HOSTNAME`env var in CI. Use the latest osixia/openldap
See similar fix in https://github.com/owncloud/phoenix/pull/3738
=> [Tests-Only] Use latest osixia/openldap in CI

docs/testing.md
these configurations seem to be needed because in that environment the proxy does not get started
=> [skip-ci] add REVA_FRONTEND_URL & REVA_DATAGATEWAY_URL conf

docs/testing.md
This PR mentions new tags: `@skipOnOcis-EOS-Storage` and `@skipOnOcis-OC-Storage` in the testing docs
- Fixes #345
=> Improve documentation to mention new skip tags

changelog/unreleased/make-frontend-prefixes-configurable.md, pkg/command/frontend.go, pkg/config/config.go, pkg/flagset/frontend.go
We introduce three new environment variables and preconfigure them the following way:
```
REVA_FRONTEND_DATAGATEWAY_PREFIX="data"
REVA_FRONTEND_OCDAV_PREFIX=""
REVA_FRONTEND_OCS_PREFIX="ocs"
```
This restores the reva defaults that were changed upstream.
https://github.com/cs3org/reva/pull/936/files#diff-51bf4fb310f7362f5c4306581132fc3bR63
=> make frontend prefixes configurable

.drone.star, changelog/unreleased/update-reva-to-20200709.md, go.mod, go.sum
Also update the test commit
Brings in a bunch of sharing fixes and file id leak fix.
=> Update reva to 20200709

.drone.star
To the latest core commit (same commit as https://github.com/cs3org/reva/pull/960 ) so we are running the same set of scenarios in the API tests.
=> [Tests-Only] Bump core commit for tests

.drone.star, changelog/unreleased/update-reva-to-20200710.md, go.mod, go.sum
Brings in the reva items in the changelog. 
This will include new test code and scenario changes matching https://github.com/cs3org/reva/pull/966 from:
https://github.com/owncloud/core/pull/37674 Remove admin auth error in log when running API acceptance tests
https://github.com/owncloud/core/pull/37675 Add env var TEST_REVA
Which allows the latest core test scenarios to pass here.
```
64 scenarios (464 passed)
3359 steps (3359 passed)
6m5.92s (20.40Mb)
```
https://cloud.drone.io/owncloud/ocis-reva/662/2/6
=> Update reva to 20200710

docs/storages.md
=> more detailed storage aspects

.drone.star
This brings the core commit used for API  tests up-to-date the same as https://github.com/cs3org/reva/pull/989
=> [Tests-Only] Update owncloud/core commit id for oC10APIAcceptanceTests

changelog/unreleased/update-reva-to-20200722.md, go.mod, go.sum, pkg/command/frontend.go
part of https://github.com/owncloud/ocis-proxy/pull/75
this PR currently hardcodes the new signing support capability as true. making them configurable is tracked in https://github.com/owncloud/ocis-reva/issues/227
=> update reva for url signing

docs/storages.md
Fix for https://github.com/owncloud/ocis-reva/issues/398
Issue was a setup problem, so the documentation will help to clarify how to deploy it properly
=> Document additional restrictions for the oc storage

.drone.star
Includes these oC10APIAcceptanceTests changes from recent days:
https://github.com/owncloud/core/pull/37745 Include trailing slash when matching a suite name
https://github.com/owncloud/core/pull/37746 Refactor listFolder acceptance tests
https://github.com/owncloud/core/pull/37749 use usersHaveBeenCreated & delete UserHelper::createUser
https://github.com/owncloud/core/pull/37751 Add tests for new capabilities
https://github.com/owncloud/core/pull/37752 Skip new lock tests on old ownCloud
Bumps to the same commit id like https://github.com/cs3org/reva/pull/1030
=> [Tests-Only] Bump commit for oC10APIAcceptanceTests

.drone.star
Gets us these core acceptance test changes:
https://github.com/owncloud/core/pull/37753 only send userid and password on user creation
=> [Tests-Only] Bump core commit id for core PR 37753

.drone.star
Gets us these core acceptance test changes:
https://github.com/owncloud/core/pull/37753 only send userid and password on user creation
https://github.com/owncloud/core/pull/37756 Delete users after test ocis ocs
=> [Tests-Only] Bump core commit id for API acceptance tests

.drone.star, docs/testing.md
1) reduce the duplicated code
2) put the API test parameters in a config section
This is like what is already done in OCIS. I made the code match what is in OCIS PR https://github.com/owncloud/ocis/pull/427 That should reduce future maintenance - the parameters are in a top `config` section and the acceptance-test code has the same functions and structure.
=> [Tests-Only] Refactor .drone.star API tests

.drone.star, docs/testing.md
Updated` drone.star` and `testing.md` file for tag preview-extension-required so that preview tests won't run in ocis-rev
- Fixes https://github.com/owncloud/ocis-reva/issues/281
=> [Tests-Only] don't run preview tests in ocis-reva 

.drone.star, tests/acceptance/expected-failures.txt, tests/acceptance/features/apiOcisSpecific/apiWebdavPreviews-previews.feature, tests/acceptance/features/apiOcisSpecific/apiWebdavUpload1-uploadFile.feature
1) Remove an unused skipOnOcis tag from a local feature file
2) Skip intermittent upload etag local test scenario (it is no good running intermittent tests in CI)
3) Bump core commit id to get latest CI scripts including core PR https://github.com/owncloud/core/pull/37785
=> [Tests-Only] Bump core commit 20200812

.drone.star, docs/testing.md, tests/acceptance/expected-failures-on-EOS-storage.txt, tests/acceptance/expected-failures-on-OC-storage.txt
In preparation for running API acceptance tests with EOS  storage, have 2 expected-failures files. These can contain the expected-failures on each storage.
Note: the 2 files will have many scenarios listed that are the same, for things that fail on both OC and EOS storage. IMO that is OK, because as things get fixed they might get fixed on one storage first, and then the other. So the lists can be reduced independently when needed.
If we find that it would be better to have a common-expected-failures.txt and 2 smaller expected-failures files for specific OC and EOS storage then we can do that. But it will require changes to the core `run.sh` script to support combining multiple expected-failures files.
If this PR is OK then I will do similar in `owncloud/ocis` and `cs3org/reva`
=> [Tests-Only] Implement separate expected-failures files for OC and EOS storage

.drone.star, tests/acceptance/expected-failures-on-OC-storage.txt
Some changes were made to the `toImplementOnOcis` tag in core PR https://github.com/owncloud/core/pull/37774 so that:
- test scenarios related to group sharing are not run at the moment (most of them were already tagged `toImplementOnOcis`  but this makes it consistent by tagging a couple more scenarios)
- adjust some sharing tests to run more of them. For some `acceptShare` scenarios they currently fail, so they are added to the expected failures.
=> [Tests-Only] Bump core commit for tests 20200820

.drone.star, tests/acceptance/expected-failures-on-OC-storage.txt
1) adjust the core commit id
Gets test changes in core API tests:
https://github.com/owncloud/core/pull/37865 [Tests-Only] Improve error reporting for various tests
https://github.com/owncloud/core/pull/37866 [Tests-Only] Enable Provisioning Api Tests for OCIS
https://github.com/owncloud/core/pull/37863 [Tests-Only] Run multiple tests for trashbinFilesFolders
https://github.com/owncloud/core/pull/37868 [Tests-Only] Improve acceptance test error handling
https://github.com/owncloud/core/pull/37871 [Tests-Only] Fix case of tag notToImplementOnOCIS
https://github.com/owncloud/core/pull/37873 [Tests-Only] subadmin and app-enable-disable-list are notToImplementOnOCIS
https://github.com/owncloud/core/pull/37874 [Tests-Only] Fix add users in provisioning api when testing on ocis
2) adjust the …
=> [Tests-Only] Bump core commit 20200902

tests/acceptance/expected-failures-on-OC-storage.txt
I raised issues about why these new test scenarios fails. Add links in the expected failures file.
=> [Tests-Only] Add issue links for failing acceptSharesToSharesFolder scenarios

tests/acceptance/expected-failures-on-OC-storage.txt
`apiShareManagementBasic` suite was renamed in core, and new suites made. Expected failures for this suite were accidentally left in expected-failures-on-OC-storage. CI did not fail, because this suite never runs, so the code in CI never gets to process these at all.
Clean it up.
Note: In cs3org/reva these are correctly removed in PR https://github.com/cs3org/reva/pull/1158
=> [Tests-Only] Cleanup old entries from expected-failures-on-OC-storage

.drone.star
Gets https://github.com/owncloud/core/pull/37882 "[Tests-Only] Add some more flexible provisioning API tests for getUsers"
Note: this is "not so interesting" here in `ocis-reva` - the provisioning API does not exist, and the tests are skipped anyway.
=> [Tests-Only] Bump core commit for tests 20200914

.drone.star
Gets us:
https://github.com/owncloud/core/pull/37913 [Tests-Only] Report HTTP status when file content is wrong
That helps to see the HTTP  status of a test when the downloaded file content is wrong.
=> [Tests-Only] Bump core commit for tests 20200915
