owncloud/ocis-reva

pkg/flagset/storagehomedata.go
pkg/flagset/storageoc.go
pkg/flagset/storageocdata.go

Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>

fix default storage config

---

.drone.star

running the oC10 API tests in CI
fixed #23 
before https://github.com/owncloud/core/pull/36791 gets merged, I'm using that specific branch, but after that master should be used
in that core PR tests are skipped and marked with reva issues to indicate why they are skipped

run API tests from oC 10 in CI

---

.drone.star

[Tests-only] run LDAP as service in CI

---

.drone.star
README.md

the server is needed for fileVersions tests

[tests-only] run redis server for api tests

---

docs/_index.md
docs/building.md
docs/getting-started.md
docs/license.md
docs/users.md

as per https://github.com/owncloud/owncloud.github.io/issues/2#issuecomment-590949444
@xoxys let's try

add edit link

---

.drone.star
tests/data/testusers.ldif

[Tests-only] Run litmus test in CI

---

docs/testing.md

part of https://github.com/owncloud/ocis/issues/211

[Tests-Only] improve testing documentation

---

docs/testing.md

part of https://github.com/owncloud/ocis/issues/211

[Tests-Only] document how to use oC10 API tests for BDD in ocis

---

changelog/unreleased/145

For https://github.com/owncloud/ocis-reva/pull/145

Add missing changelog entry for 145

---

docs/testing.md

1. clarify that this is about API tests
2. make the example use an API test feature file

[Tests-only] fixtures and clarifications for API acceptance tests

---

.drone.star

This PR changes the skeleton directory path that is created by PR https://github.com/owncloud/ocis-reva/pull/185

[Tests-only] Fix skeleton directory path

---

.drone.star
tests/config/config.json
tests/config/identifier-registration.yml

- Run UI Acceptance tests with phoenix
- Refactor CI pipelines to run unit, API and UI tests in different pipelines

[Tests-Only] Run ui tests with phoenix

---

.drone.star

Run phoenix UI tests in CI with latest version of phoenix from git.

[Tests-Only] use latest version of phoenix for UI tests in CI

---

.drone.star

Mount upload directory for files upload and add missing configuration variables for reva services in Ui tests.

[Tests-Only] Fix upload UI tests in CI

---

.drone.star

Part of issue https://github.com/owncloud/ocis/issues/303
Specify the branch, and commit in that branch, to use when fetching the ownCloud10 core API test runner code.

[Tests-Only] Fetch API testrunner from specific branch and commit

---

.drone.star

skip tests tagged with the new tag in owncloud/core#37554

[tests-only] skip tests that are tagged @skipOnOcis-OC-Storage

---

.drone.star

To match up with approximately core release 10.5.0.
So  we will be running the current relevant API acceptance tests.

[Tests-Only] Bump core commit for API tests

---

.drone.star

Similar to https://github.com/owncloud/ocis/pull/342

[Tests-Only] Adjust apiTests to use core commit

---

changelog/unreleased/allow-datagateway-transfers-24h.md
pkg/flagset/gateway.go

Allow datagateway transfers to take 24h

Increase transfer token life time to 24h

---

.drone.star

when running acceptance tests.

[Tests-Only] Use latest commit from core master

---

.drone.star

The same as https://github.com/cs3org/reva/pull/1015
It gets us test scenarios that have been added/changed over the past week:
https://github.com/owncloud/core/pull/37717 Add EXPECTED_FAILURES_FILE capability to acceptance tests run.sh (I  will make a proposed PR to use that capability later this week)
https://github.com/owncloud/core/pull/37721 Modify functions to check the presence of files and folders - does more strict checking when a resource should be a file and not a folder or vice-versa

[Tests-Only] Bump commit id for apiTests

---

.drone.star

To include:
https://github.com/owncloud/core/pull/37740 Remove skipOnOcis tag for scenarios not to be skipped on ocis
https://github.com/owncloud/core/pull/37742 Fix tests for ocis with proxy

[Tests-Only] Bump commit id for oC10APIAcceptanceTests

---

.drone.star
tests/acceptance/expected-failures.txt
tests/acceptance/features/apiOcisSpecific/apiWebdavUpload1-uploadFile.feature

and bump the core commit to be current.

[Tests-Only] Add new uploadFile bug demo scenario from core PR 37795

---

.drone.star
tests/acceptance/expected-failures.txt
tests/acceptance/features/apiOcisSpecific/apiWebdavUpload1-uploadFile.feature

and adjust the expected failures.
And comment out a test scenario example that is intermittent.

[Tests-Only] Bump core commit id for removed bug demo scenarios

---

.drone.star
tests/acceptance/expected-failures.txt

Gets the tests running that were enabled in core PR https://github.com/owncloud/core/pull/37809

[Tests-Only] Bump core commit to run extra tests

---

.drone.star

Includes core test changes:
https://github.com/owncloud/core/pull/37839 [Tests-Only] Assert created user
https://github.com/owncloud/core/pull/37849 [Tests-Only] remove UI tests from expected failures if rerun is successful
https://github.com/owncloud/core/pull/37847 [Tests-Only] Improve header response checks in theHeaderChecksumShoudMatch
https://github.com/owncloud/core/pull/37851[Tests-Only] Fix theseUsersHaveBeenCreatedUsingTheOccCommand so it works with mixed-case usernames
https://github.com/owncloud/core/pull/37855 [Tests-Only] Process unexpected Behat exit status in acceptance tests
https://github.com/owncloud/core/pull/37852 [Tests-Only] Reporting expected failures when running a single feature

[Tests-Only] Bump oC10 test commit id

---

.drone.star
tests/acceptance/expected-failures-on-OC-storage.txt

Gets us these core test changes:
https://github.com/owncloud/core/pull/37879 [Tests-Only] Remove some toImplementOnOCIS tags
https://github.com/owncloud/core/pull/37880 [Tests-Only] Make scenario outline for creating a share with no permissions
https://github.com/owncloud/core/pull/37889 [Tests-Only] Acceptance tests for issue 37883

[Tests-Only] Bump core commit
